### ISSUE TITLE
Checklist for submission

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy-tutorial#14]
- [x] adding final version of data (polynesian.tsv)
- [x] installation section (with additional libraries, probably only "segments" and "pycldf" and python-igraph)
- [x] check and synchronize section 4 in tutorial-online with tutorial-draft
- [x] 4.5 intro on inspection with edictor (maybe add screenshot)
- [x] 4.6 also do this section with edictor (add screenshot)
- [x] 5.1 explain the structure of the "DIFF" file in bcubes / lingpy.evaluate
- [x] 5.3 code for "benefits of segmentation" needs update
- [x] 6.1 nexus export (add section, export is already in lingpy)
- [x] 6.2 consider dropping this part, as it is not discussed in tutorial
- [x] 6.3 cldf export: add section, lingpy needs function for cldf-import, export to cldf is done via @xrotwang's code
- [x] add references, delete links to "evobib"
- [x] submit lingpy-2.6
- [x] official release of segments package
- [x] small pypi version of pycldf for reference in the tutorial
- [x] small cldf-version (paper-less, but needed to reference in the tutorial main paper as, say Forkel et al. 2017)
- [ ] convert to pdf via markdown and pandoc (tedious, but needs to be done to ease submission, some reviewers won't look at the notebook)
- [x] upload data and code to osf.io to allow for anonymous review
- [ ] change paper by adding lumper and splitter instead of the random cognate detection, as this is more telling
